--- 
title: "A maximal self tutorial"
author: "Kadir Göçer"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a maximal example of using the bookdown package to write a self tutorial. The output format for this example is bookdown::gitbook."
---

# Prerequisites

This is a _sample_ tutorial written in **Markdown** to understand the basics of reproducible research and using some of packages like: dplyr [@R-dplyr], tidyr, ggplot.

* Rmarkdown: Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
* Git: Git is a free and open source distributed version control system <https://git-scm.com>.
* R: R is a free software environment for statistical computing and graphics. It compiles and runs on a wide variety of UNIX platforms, Windows and MacOS <https://www.r-project.org>.
* Rstudio: RStudio is an integrated development environment (IDE) for R <https://www.rstudio.com/products/RStudio>. 
* Github: GitHub is a web-based Git repository hosting service <https://github.com>.
* LinuxMint: Linux Mint is a community-driven Linux distribution based on Debian and Ubuntu <https://www.linuxmint.com>

